# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-xuyanghaha-github-io-Guu'

google-ID: 'UA-112060364-1'

menu:
#- {name: '关于', path: 'menu', url: 'about.html'}
- {name: '文章列表', path: 'menu', url: 'writing.html'}
#- {name: '联系方式', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
#- {icon: 'github', link: 'https://www.github.com/xuyanghaha'}
#- {icon: 'linkedin', link: 'http://www.linkedin.com/in/lenpaul/'}
#- {icon: 'rss-square', link: 'feed.xml'}
#- {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: '最近'
  previous_page: '更早'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
